/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample_sub_project;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("This is a library.");
        return true;
    }
}
